version: '3.7'
services:
  x86_64-apple-darwin:
    image: flash-rover/crossbuild:x86_64-apple-darwin
    build:
      context: ./scripts/docker/x86_64-apple-darwin
      dockerfile: Dockerfile
    working_dir: /project
    volumes:
      - .:/project
    hostname: flash-rover

networks:
  default:
    external:
      name: bridge
