#!/bin/bash

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"

UNAME_OUT="$(uname -s)"

case "${UNAME_OUT}" in
    Darwin*)
        LIBJVM_PATH=${CURR_DIR}/../../eclipse/Ccstudio.app/jre/Contents/Home/lib/server
        LIBJVM_NAME=libjvm.dylib
        ;;
    Linux* | *)
        LIBJVM_PATH=${CURR_DIR}/../../eclipse/jre/lib/amd64/server
        LIBJVM_NAME=libjvm.so
        ;;
esac

if [ ! -f "${LIBJVM_PATH}/${LIBJVM_NAME}" ]; then
    echo "libjvm path configured in flash-rover is wrong, please verify LIBJVM_PATH is correct before continuing"
    exit 1
fi

LD_LIBRARY_PATH=${LIBJVM_PATH}${LD_LIBRARY_PATH:+:$LD_LIBRARY_PATH}
export LD_LIBRARY_PATH

exec "$CURR_DIR/ti-xflash" "$@"
