#!/bin/bash

CURR_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
CCS_ROOT=${CURR_DIR}/../..

UNAME_OUT="$(uname -s)"

case "${UNAME_OUT}" in
    Darwin*)
        LIBJVM_PATH=${CCS_ROOT}/eclipse/Ccstudio.app/jre/Contents/Home/lib/jli
        LIBJVM_NAME=libjli.dylib
        ;;
    Linux* | *)
        LIBJVM_PATH=${CCS_ROOT}/eclipse/jre/lib/amd64/server
        LIBJVM_NAME=libjvm.so
        ;;
esac

if [ ! -f "${LIBJVM_PATH}/${LIBJVM_NAME}" ]; then
    echo "libjvm path configured in flash-rover is wrong, please verify LIBJVM_PATH is correct before continuing"
    exit 1
fi

export LD_LIBRARY_PATH=${LIBJVM_PATH}

exec "$CURR_DIR/ti-xflash" "$@"
