[package]
name = "flash-rover"
version = "0.1.0"
authors = ["Texas Instruments <ti.com>"]
edition = "2018"
build = "build.rs"

[build-dependencies]
walkdir = "2"

[dependencies]
clap = "2.33"
failure = "0.1"
path-clean = "0.1"
byte-unit = "3.0"
