[package]
name = "dss"
version = "0.1.0"
authors = ["Texas Instruments <ti.com>"]
edition = "2018"

[dependencies]
path-clean = "0.1"
path-slash = "0.1"

[dependencies.jni]
version = "0.14"
features = ["invocation"]
